{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "self.fullname" . }}
  labels:
 {{ include "self.labels" . | indent 4 }}
data:
  KUBERNETES_NAMESPACE: {{ .Release.Namespace }}
  KUBERNETES_SERVICES: {{ template "self.fullname" . }}
#allowing env vars from values files to be added as name/value pairs with optional release prefixing
  {{- range $prop := .Values.dependencyConfigProps }}
  {{- if $prop.releasePrefixValue }}
  {{ $prop.name }}: {{ $releaseName }}-{{ $prop.propValue }}
  {{- else }}
  {{ $prop.name }}: {{ $prop.propValue | quote }}
  {{- end }}
  {{- end }}