{{- if .Values.persistentVolume.pvEnabled -}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "self.fullname" . }}
  labels:
{{ include "self.labels" . | indent 4 }}
    purpose: {{ .Values.persistentVolume.purpose }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  hostPath:
      path: {{ .Values.persistentVolume.basePath }}/{{ .Release.Namespace }}/{{ template "self.fullname" . }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  persistentVolumeReclaimPolicy: Retain
{{- end }}