{{- if .Values.rbac.enabled -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "self.fullname" . }}-endpoint-lookup
  labels:
{{ include "self.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["endpoints"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "self.fullname" . }}-endpoint-lookup
  labels:
{{ include "self.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "self.fullname" . }}-endpoint-lookup
subjects:
  - kind: ServiceAccount
    name: {{ template "self.fullname" . }}-{{ .Values.rbac.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{- end }}
