{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "self.fullname" . }}-{{ .Values.rbac.serviceAccount }}
  labels: 
{{ include "self.labels" . | indent 4 }}
{{- end }}