{{- $fullName := include "self.fullname" . -}}
{{- $k8sVer := .Capabilities.KubeVersion.GitVersion -}}
{{- if .Values.ingress.mgmt.internal.enabled -}}
{{- if semverCompare ">=1.19-0" $k8sVer -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-mgmt-int
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.mgmt.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.mgmt.internal.ingressClassName }}
  ingressClassName: {{ .Values.ingress.mgmt.internal.ingressClassName }}
{{- end }}
{{- if .Values.ingress.mgmt.internal.tls }}
  tls:
  {{- range .Values.ingress.mgmt.internal.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.mgmt.internal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: Prefix
            backend:
            {{- if semverCompare ">=1.19-0" $k8sVer }}
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .servicePort | quote }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
            {{- end }}           
        {{- end }}
  {{- end }}
{{- end }} 
---
{{- if .Values.ingress.mgmt.external.enabled -}}
{{- if semverCompare ">=1.19-0" $k8sVer -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-mgmt-ext
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.mgmt.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.mgmt.external.ingressClassName }}
  ingressClassName: {{ .Values.ingress.mgmt.external.ingressClassName }}
{{- end }}
{{- if .Values.ingress.mgmt.external.tls }}
  tls:
  {{- range .Values.ingress.mgmt.external.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.mgmt.external.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: Prefix
            backend:
            {{- if semverCompare ">=1.19-0" $k8sVer }}
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .servicePort | quote }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
            {{- end }}           
        {{- end }}
  {{- end }}
{{- end }}  
---
{{- if .Values.ingress.data.external.enabled -}}
{{- if semverCompare ">=1.19-0" $k8sVer -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-data-ext
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.data.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.data.external.ingressClassName }}
  ingressClassName: {{ .Values.ingress.data.external.ingressClassName }}
{{- end }}
{{- if .Values.ingress.data.external.tls }}
  tls:
  {{- range .Values.ingress.data.external.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.data.external.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: Prefix
            backend:
            {{- if semverCompare ">=1.19-0" $k8sVer }}
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .servicePort | quote }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
            {{- end }}           
        {{- end }}
  {{- end }}
{{- end }}
---
{{- if .Values.ingress.data.internal.enabled -}}
{{- if semverCompare ">=1.19-0" $k8sVer -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-data-int
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.data.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.data.internal.ingressClassName }}
  ingressClassName: {{ .Values.ingress.data.internal.ingressClassName }}
{{- end }}
{{- if .Values.ingress.data.internal.tls }}
  tls:
  {{- range .Values.ingress.data.internal.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.data.internal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: Prefix
            backend:
            {{- if semverCompare ">=1.19-0" $k8sVer }}
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .servicePort | quote }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
            {{- end }}           
        {{- end }}
  {{- end }}
{{- end }}