{{- $fullName := include "self.fullname" . -}}
{{- if .Values.ingress.apiServer.internal.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-api-int
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.apiServer.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.apiServer.internal.ingressClassName }}
  ingressClassName: {{ .Values.ingress.apiServer.internal.ingressClassName }}
{{- end }}
{{- if .Values.ingress.apiServer.internal.tls }}
  tls:
  {{- range .Values.ingress.apiServer.internal.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.apiServer.internal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
        {{- end }}
  {{- end }}
{{- end }} 
---
{{- if .Values.ingress.apiServer.external.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-api-ext
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.apiServer.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.apiServer.external.ingressClassName }}
  ingressClassName: {{ .Values.ingress.apiServer.external.ingressClassName }}
{{- end }}
{{- if .Values.ingress.apiServer.external.tls }}
  tls:
  {{- range .Values.ingress.apiServer.external.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.apiServer.external.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
        {{- end }}
  {{- end }}
{{- end }}  
---
{{- if .Values.ingress.tokenServer.external.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-token-ext
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.tokenServer.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tokenServer.external.ingressClassName }}
  ingressClassName: {{ .Values.ingress.tokenServer.external.ingressClassName }}
{{- end }}
{{- if .Values.ingress.tokenServer.external.tls }}
  tls:
  {{- range .Values.ingress.tokenServer.external.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.tokenServer.external.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
        {{- end }}
  {{- end }}
{{- end }}
---
{{- if .Values.ingress.tokenServer.internal.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-token-int
  labels:
{{ include "self.labels" . | indent 4 }}
  {{- with .Values.ingress.tokenServer.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tokenServer.internal.ingressClassName }}
  ingressClassName: {{ .Values.ingress.tokenServer.internal.ingressClassName }}
{{- end }}
{{- if .Values.ingress.tokenServer.internal.tls }}
  tls:
  {{- range .Values.ingress.tokenServer.internal.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.tokenServer.internal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path | quote }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort | quote }}
        {{- end }}
  {{- end }}
{{- end }}